name: CI

# Controls when the workflow will run
on:
  # Trigger the workflow on push or pull request,
  # but only for the ios-dev branch.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app && /usr/bin/xcodebuild -version
    - name: Run unit tests
      run: xcodebuild test -project ci.xcodeproj -scheme ci -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.4' | xcpretty && exit ${PIPESTATUS[0]}

