# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Trigger the workflow on push or pull request,
  # but only for the ios-dev branch.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.3.app && /usr/bin/xcodebuild -version
    - name: Run unit tests
      run: xcodebuild test -project ci/ci.xcworkspace -scheme ci -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.4' | xcpretty && exit ${PIPESTATUS[0]}

